### ISSUE TITLE
refactor: standardize include guards across all header files

### ISSUE THREAD

**Issue by NaisargPurohit** [darshan2456/C_DSA_interactive_suite#1288]
Description of the Problem:
With the rapid expansion of the codebase across various directories (graphs, trees, sorting, etc.), the #ifndef / #define header guards in the .h files can become inconsistent in naming conventions. Inconsistent or duplicate header guards risk multiple-inclusion compilation errors.

Proposed Solution:
I will run through the core header files in the src/ directory and ensure all include guards follow a strict, unified naming convention (e.g., MODULE_FILENAME_H). This is a pure refactor that ensures C compilation best practices and prevents future cyclic dependency issues.

**Comment by NaisargPurohit** [comment]
I'd like to work on this issue , could you please assign this issue to me.

**Comment by NaisargPurohit** [comment]
please assign me

**Comment by darshan2456** [comment]
@NaisargPurohit explain what exactly you will do with an example

**Comment by NaisargPurohit** [comment]
Absolutely! Right now, some of the header files use very generic include guards. For example, in src/data_structures/array.h, the guard is currently:
#ifndef ARRAY_H
#define ARRAY_H

While this works in isolation, generic names like ARRAY_H or NODE_H run a high risk of colliding with other libraries or future modules as the project grows. If two different headers end up using #ifndef ARRAY_H, the compiler will silently ignore the second one, leading to missing declaration errors that are notoriously frustrating to debug.

What I will do:
I will go through the headers in the src/ directory and update the guards to follow a strict [MODULE]_[FILENAME]_H naming convention.

Using array.h as the example, I would update it to include its parent directory for guaranteed uniqueness:

#ifndef DATA_STRUCTURES_ARRAY_H
#define DATA_STRUCTURES_ARRAY_H

This is a standard C/C++ best practice that guarantees every header guard is universally unique across the entire project. Does this [MODULE]_[FILENAME]_H format work for you, or do you have a different preferred prefix?"

**Comment by darshan2456** [comment]
@NaisargPurohit I got your idea, but the problem you pointed out is very difficult to occur in the current project. Like there are no two files with the exact same name. so once we implement stack or dll, all future refactors will be within that file only. There is little to no chance of duplication right? So problem doesnt exist and if we change something as pivotal as header declarations that has great chances of breaking things. So I dont think it is worth the effort

**Comment by NaisargPurohit** [comment]
That makes complete sense! You make a great point—if the file names are globally unique by design, the risk of a collision is basically zero. I completely agree that it's not worth the refactoring risk in that case.

Thank you for taking the time to discuss it with me! I will go ahead and close this issue to keep your tracker clean.
